import{a as b,i as u,S as E}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function l(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=l(t);fetch(t.href,s)}})();const S="https://pixabay.com/api/",w="42750421-25533ceabe92b3d649fd552d3";async function g(r,e){const l={key:w,q:r,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await b.get(`${S}`,{params:l})).data}function p(r){return r.map(e=>`<li class="gallery-item">
       <a href="${e.largeImageURL}">
    <img src='${e.largeImageURL}' alt='${e.tags}' class='gallery-img' /></a>
    <div class = "gallery-section">
    <p class="gallery-text">Like<span class= "value">${e.likes}</span></p>
   <p class="gallery-text">Views<span class= "value">${e.views}</span></p>
    <p class="gallery-text">Comments<span class= "value">${e.comments}</span></p>
     <p class="gallery-text">Downloads<span class= "value">${e.downloads}</span></p>
     
    </li>`).join("")}const i=document.querySelector(".js-gallery"),P=document.querySelector(".js-search-form"),y=document.querySelector(".loader"),m=document.querySelector(".js-load-more");P.addEventListener("submit",M);m.addEventListener("click",x);let a=1,o,h=15;async function M(r){if(r.preventDefault(),a=1,i.innerHTML="",v(),o=r.currentTarget.elements["user-search-query"].value.trim(),!o)return f(),n(),u.error({title:"Error",message:"error"});try{const e=await g(o,a);if(e.hits.length===0)return n(),u.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});i.innerHTML=p(e.hits),L.refresh(),e.totalHits<h?n():$()}catch(e){console.log(e)}finally{f(),r.target.reset()}}async function x(){v(),a+=1;try{const r=await g(o,a);Math.ceil(r.totalHits/h)===a&&(n(),u.error({title:"Error",message:"Sorry, thats all"})),i.insertAdjacentHTML("beforeend",p(r.hits)),L.refresh(),q()}catch{console.log("error")}finally{f()}}const L=new E(".gallery a",{captionsData:"alt",captionDelay:250});function v(){y.classList.remove("is-hidden")}function f(){y.classList.add("is-hidden")}function $(){m.classList.remove("is-hidden")}function n(){m.classList.add("is-hidden")}function q(){const e=i.firstElementChild.getBoundingClientRect().height*2;scrollBy({behavior:"smooth",top:e})}
//# sourceMappingURL=commonHelpers.js.map
